### PR TITLE
Added reset functionality 

### LINKED ISSUE #2: add a reset button
this button should clear all the text and the image

### PR DESCRIPTION
**Pull request by harshN-17**
Fixed #2 
added a reset button that clears the input text field and the image and its texts too.
added two useStates for each input field to set the empty after reset button is clicked.
minor fix:
added 'alt' attribute in the img tag which was giving warning

### CODE REVIEW

**Comment by DuP-491** [comment]
@harshN-17 mention issue number

**Comment by harshN-17** [comment]
@DuP-491 I have mentioned the issue number

**Comment by DuP-491** [comment]
@harshN-17 there were bugs I have encountered

- Placeholder text in forms after reset is vanishing
- After reset upload image feature is not working

**Comment by harshN-17** [comment]
@DuP-491 I purposely made the placecholder vanish as it said 'to clear the texts' but will fix the quickly. Meanwhile I will also try to word on the second bug

**Comment by harshN-17** [comment]
@DuP-491 I looked at the second bug you mentioned. The code works fine if we upload different file. But it does not take action for the same file. (before or after reset)
It seems like this bug already existed. 
Since there is a call of onChange function on file input it does not get triggered if we upload same file consecutively.

**Comment by DuP-491** [comment]
@harshN-17 changing clearing text does not mean removing placeholder

**Comment by harshN-17** [comment]
Kindly check my latest commit.

**Comment by DuP-491** [comment]
LGTM!

**Pull request merged**
