### PR TITLE
Added facility to add more text and also delete them

### LINKED ISSUE #8: facility to add more text and also delete them
currently, the user can only provide two text inputs. Implement the feature to add more text and also add a delete button on every text

### PR DESCRIPTION
**Pull request by sanskaromar**
Fixes issue #8

### CODE REVIEW

**Comment by dev-lovedeep** [comment]
mention the issue number

**Comment by sanskaromar** [comment]
Fixes issue #8

**Comment by dev-lovedeep** [comment]
> @dev-lovedeep Fixes issue #8

what i am expecting of the UI is , you have only one input box and when you hit enter it shows the text on screen

for deleting: when you hover over the text, a small cross button should be shown on top left , when clicked will delete that text item

**Comment by dev-lovedeep** [comment]
@sanskaromar are you working on this issue?

**Review by dev-lovedeep — APPROVED** [review]

**Pull request closed without merging**
